version: "3.8"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5430:5430"
    volumes:
      - ./server/db-data/:/var/lib/postgresql/data/
    env_file:
      - ./server/.env
    expose:
      - 5430

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    env_file:
      - ./server/.env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./server/src:/server/src

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "5173:5173"

volumes:
  pgdata:
